"""create full initial schema

Revision ID: 227c1ff91039
Revises: 
Create Date: 2026-08-01 21:44:31.173178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '227c1ff91039'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('target_table', sa.Text(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_audit_log'))
    )
    op.create_table('company_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sector', sa.Text(), nullable=False),
    sa.Column('name_pool', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('backstory_pool', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('base_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unique_strength', sa.Text(), nullable=False),
    sa.Column('unique_weakness', sa.Text(), nullable=False),
    sa.Column('unique_passive_ability', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_templates'))
    )
    op.create_table('event_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('response_options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weight', sa.Numeric(), server_default='1.0', nullable=False),
    sa.Column('min_quarter', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('applicable_sectors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_chain_trigger', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('follow_up_template_id', sa.UUID(), nullable=True),
    sa.Column('late_quarter_only', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cooldown_span', sa.SmallInteger(), server_default='2', nullable=False),
    sa.ForeignKeyConstraint(['follow_up_template_id'], ['event_templates.id'], name=op.f('fk_event_templates_follow_up_template_id_event_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_templates'))
    )
    op.create_table('game_control_flags',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('paused', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('emergency_stop', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('leaderboard_frozen', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_control_flags')),
    sa.UniqueConstraint('scope', name='scope')
    )
    op.create_table('players',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('prn', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('department', sa.Text(), nullable=False),
    sa.Column('year_of_study', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('prn', name=op.f('uq_players_prn'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('current_quarter', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('current_stage', sa.Text(), server_default='briefing', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_number', sa.SmallInteger(), server_default='1', nullable=False),
    sa.CheckConstraint("current_stage IN ('briefing','planning','events','board','report')", name=op.f('ck_sessions_current_stage_valid_values')),
    sa.CheckConstraint("status IN ('active','fired','bankrupt','completed','abandoned')", name=op.f('ck_sessions_status_valid_values')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_sessions_player_id_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('was_blocked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_ai_conversations_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_conversations'))
    )
    op.create_table('companies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sector', sa.Text(), nullable=False),
    sa.Column('backstory', sa.Text(), nullable=False),
    sa.Column('unique_strength', sa.Text(), nullable=False),
    sa.Column('unique_weakness', sa.Text(), nullable=False),
    sa.Column('unique_passive_ability', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_companies_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['company_templates.id'], name=op.f('fk_companies_template_id_company_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_table('corporate_times_issues',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False),
    sa.Column('top_companies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('biggest_failures', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('market_events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('board_gossip', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('economic_outlook', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_corporate_times_issues_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corporate_times_issues'))
    )
    op.create_table('leaderboard',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=False),
    sa.Column('sector', sa.Text(), nullable=False),
    sa.Column('final_score', sa.Numeric(), nullable=True),
    sa.Column('revenue_score', sa.Numeric(), nullable=True),
    sa.Column('satisfaction_score', sa.Numeric(), nullable=True),
    sa.Column('innovation_score', sa.Numeric(), nullable=True),
    sa.Column('investor_score', sa.Numeric(), nullable=True),
    sa.Column('survival_score', sa.Numeric(), nullable=True),
    sa.Column('risk_penalty', sa.Numeric(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('excluded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_leaderboard_player_id_players'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_leaderboard_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leaderboard'))
    )
    op.create_index('ix_leaderboard_score_ranked', 'leaderboard', [sa.literal_column('final_score DESC')], unique=False, postgresql_where=sa.text('NOT excluded'))
    op.create_table('market_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False),
    sa.Column('oil_price', sa.Numeric(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(), nullable=False),
    sa.Column('inflation', sa.Numeric(), nullable=False),
    sa.Column('commodity_index', sa.Numeric(), nullable=False),
    sa.Column('currency_index', sa.Numeric(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_market_snapshots_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_snapshots'))
    )
    op.create_table('board_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False),
    sa.Column('trigger_reason', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_board_sessions_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board_sessions'))
    )
    op.create_table('budget_allocations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_budget_allocations_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_allocations'))
    )
    op.create_index('ix_budget_company_quarter_category', 'budget_allocations', ['company_id', 'quarter', 'category'], unique=False)
    op.create_table('company_states',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False),
    sa.Column('cash', sa.Numeric(), nullable=False),
    sa.Column('revenue', sa.Numeric(), nullable=False),
    sa.Column('profit', sa.Numeric(), nullable=False),
    sa.Column('debt', sa.Numeric(), nullable=False),
    sa.Column('stock_price', sa.Numeric(), nullable=False),
    sa.Column('employees', sa.Integer(), nullable=False),
    sa.Column('innovation', sa.Numeric(), nullable=False),
    sa.Column('brand', sa.Numeric(), nullable=False),
    sa.Column('client_satisfaction', sa.Numeric(), nullable=False),
    sa.Column('employee_satisfaction', sa.Numeric(), nullable=False),
    sa.Column('investor_confidence', sa.Numeric(), nullable=False),
    sa.Column('esg', sa.Numeric(), nullable=False),
    sa.Column('risk', sa.Numeric(), nullable=False),
    sa.Column('market_share', sa.Numeric(), nullable=False),
    sa.Column('board_confidence', sa.Numeric(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_states_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_states')),
    sa.UniqueConstraint('company_id', 'quarter', name='uq_company_states_company_quarter')
    )
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False),
    sa.Column('client_name', sa.Text(), nullable=False),
    sa.Column('client_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='incoming', nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('relationship_score', sa.Numeric(), server_default='50', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_contracts_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts'))
    )
    op.create_table('decision_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False),
    sa.Column('decision_type', sa.Text(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('stat_deltas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_decision_log_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_log'))
    )
    op.create_table('event_instances',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chosen_option_index', sa.SmallInteger(), nullable=True),
    sa.Column('resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('response_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_event_instances_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['event_templates.id'], name=op.f('fk_event_instances_template_id_event_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_instances'))
    )
    op.create_index('ix_event_instances_company_quarter_resolved', 'event_instances', ['company_id', 'quarter', 'resolved'], unique=False)
    op.create_table('pending_chain_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('due_quarter', sa.SmallInteger(), nullable=False),
    sa.Column('consumed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_pending_chain_events_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['event_templates.id'], name=op.f('fk_pending_chain_events_template_id_event_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_chain_events'))
    )
    op.create_index('ix_pending_chain_due', 'pending_chain_events', ['company_id', 'due_quarter'], unique=False, postgresql_where=sa.text('NOT consumed'))
    op.create_table('quarter_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False),
    sa.Column('kpi_deltas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_quarter_reports_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quarter_reports')),
    sa.UniqueConstraint('company_id', 'quarter', name='uq_quarter_reports_company_quarter')
    )
    op.create_table('board_exchanges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('board_session_id', sa.UUID(), nullable=False),
    sa.Column('speaker', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('chosen_response', sa.Text(), nullable=True),
    sa.Column('confidence_delta', sa.Numeric(), nullable=True),
    sa.Column('sequence', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['board_session_id'], ['board_sessions.id'], name=op.f('fk_board_exchanges_board_session_id_board_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board_exchanges'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_exchanges')
    op.drop_table('quarter_reports')
    op.drop_index('ix_pending_chain_due', table_name='pending_chain_events', postgresql_where=sa.text('NOT consumed'))
    op.drop_table('pending_chain_events')
    op.drop_index('ix_event_instances_company_quarter_resolved', table_name='event_instances')
    op.drop_table('event_instances')
    op.drop_table('decision_log')
    op.drop_table('contracts')
    op.drop_table('company_states')
    op.drop_index('ix_budget_company_quarter_category', table_name='budget_allocations')
    op.drop_table('budget_allocations')
    op.drop_table('board_sessions')
    op.drop_table('market_snapshots')
    op.drop_index('ix_leaderboard_score_ranked', table_name='leaderboard', postgresql_where=sa.text('NOT excluded'))
    op.drop_table('leaderboard')
    op.drop_table('corporate_times_issues')
    op.drop_table('companies')
    op.drop_table('ai_conversations')
    op.drop_table('sessions')
    op.drop_table('players')
    op.drop_table('game_control_flags')
    op.drop_table('event_templates')
    op.drop_table('company_templates')
    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
